# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

f1 = 1  # first term in Fibonacci sequence
f2 = 2  # second term in Fibonacci sequence
total = 0

while f2 <= 4000000:  # stops from going over 4 million
    if f2 % 2 == 0:  # checks if even-valued
        total += f2
    temp = f2  # store the second term to a temporary term
    f2 += f1  # adds the second and first term together to get your new second term
    f1 = temp  # replaces the first term with second term

print(total)
